# Generated by Django 3.1.4 on 2020-12-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20201227_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30, null=True)),
                ('id1', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('collegename', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('Mech', 'Mech')], max_length=20)),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
    ]
