# Generated by Django 3.1.4 on 2020-12-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_auto_20201227_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='stufac',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
