# Generated by Django 3.1.4 on 2020-12-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_stufac_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stufac',
            old_name='collegename',
            new_name='fac_collegename',
        ),
        migrations.RenameField(
            model_name='stufac',
            old_name='department',
            new_name='fac_department',
        ),
        migrations.RenameField(
            model_name='stufac',
            old_name='email',
            new_name='fac_email',
        ),
        migrations.RenameField(
            model_name='stufac',
            old_name='name',
            new_name='fac_name',
        ),
        migrations.RenameField(
            model_name='stufac',
            old_name='password',
            new_name='fac_password',
        ),
        migrations.AddField(
            model_name='stufac',
            name='rollno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stufac',
            name='stu_collegename',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stufac',
            name='stu_department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('Mech', 'Mech')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stufac',
            name='stu_email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stufac',
            name='stu_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stufac',
            name='stu_password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
