# Generated by Django 3.1.4 on 2020-12-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_auto_20201228_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stufac',
            name='fac_department',
        ),
    ]
