# Generated by Django 3.1.4 on 2020-12-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_remove_stufac_fac_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='stufac',
            name='fac_department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('Mech', 'Mech')], max_length=20, null=True),
        ),
    ]
